version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: warung-pos-db
    environment:
      POSTGRES_DB: warung_pos
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./backend
    container_name: warung-pos-api
    environment:
      DATABASE_URL: postgresql://postgres@postgres:5432/warung_pos
      JWT_SECRET: ${JWT_SECRET:-change-me-in-production}
      PORT: 3001
      NODE_ENV: production
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
